# ?? ?? ??
server:
  port: 8085

# ??? ?? ??
spring:

  devtools: # 8-11
    livereload:
      enabled: true

    freemarker: # 8-12
      cache: false

    thymeleaf: # 8-13
      cache: false


# DB ??
datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/langCM02?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull&connectTimeout=60
  username: jeon
  password: youngmin

# jpa ??
jpa:
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      show_sql: true
      format_sql: true
    open-in-view: true